For BERT dynamic embedding

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Data Loading

In [ ]:
!pip install datasets

INFO: pip is looking at multiple versions of multiprocess to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 11.4 MB/s eta 0:00:00


In [ ]:
from datasets import load_dataset

# Load the dataset
dataset = load_dataset("0xAIT/SIDAC")

# Access the train and test splits (if available)
texts = dataset['train']

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


README.md:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.


Resolving data files:   0%|          | 0/17 [00:00<?, ?it/s]

data-00000-of-00016.arrow:   0%|          | 0.00/499M [00:00<?, ?B/s]

data-00001-of-00016.arrow:   0%|          | 0.00/504M [00:00<?, ?B/s]

data-00002-of-00016.arrow:   0%|          | 0.00/497M [00:00<?, ?B/s]

data-00003-of-00016.arrow:   0%|          | 0.00/509M [00:00<?, ?B/s]

data-00004-of-00016.arrow:   0%|          | 0.00/502M [00:00<?, ?B/s]

data-00005-of-00016.arrow:   0%|          | 0.00/507M [00:00<?, ?B/s]

data-00006-of-00016.arrow:   0%|          | 0.00/499M [00:00<?, ?B/s]

data-00007-of-00016.arrow:   0%|          | 0.00/503M [00:00<?, ?B/s]

data-00008-of-00016.arrow:   0%|          | 0.00/503M [00:00<?, ?B/s]

data-00009-of-00016.arrow:   0%|          | 0.00/498M [00:00<?, ?B/s]

data-00010-of-00016.arrow:   0%|          | 0.00/506M [00:00<?, ?B/s]

data-00011-of-00016.arrow:   0%|          | 0.00/505M [00:00<?, ?B/s]

data-00012-of-00016.arrow:   0%|          | 0.00/573M [00:00<?, ?B/s]

data-00013-of-00016.arrow:   0%|          | 0.00/384M [00:00<?, ?B/s]

data-00014-of-00016.arrow:   0%|          | 0.00/233M [00:00<?, ?B/s]

data-00015-of-00016.arrow:   0%|          | 0.00/326M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
# # Extract a small portion
# texts = texts[:1000]['text']

# print(texts[0:5])

['පොලිස් කොමිසමෙන් පියන් කෙනකු කළ ශානිගේ කතාව. - Info Sri Lanka News | Sinhala\nHome Featured features Top පොලිස් කොමිසමෙන් පියන් කෙනකු කළ ශානිගේ කතාව.\nගෝඨාභය රාජපක්ෂ යනු හිටපු හමුදා නිලධාරියෙකි. පසු කලෙක ආරක්ෂක අමාත්\u200dයාංශයේ ලේකම්වරයා වශයෙන්\u2009ද කටයුතු කළ අයෙකි. දැන් මෙරට ජනාධිපතිවරයාය. ඔහු ජනාධිපතිවරණ සටනේදී පුන පුනා කීවේ පැවැති ආණ්ඩුව ඔවුන් විසින් \'රණවිරුවන්\' ලෙසින් හැඳින්\u2009වූ අයව දඩයම් කරන බවය. එනිසා එකී දඩයක්කාර ආණ්ඩුව ගෙදර යැවිය යුතු බව ඔවුන්ගේ මැතිවරණයේ ප්\u200dරධාන සටන් පාඨය විය. දැන් ඒ ආණ්ඩුව ගෙදර ගොස් ඇත. ඇත්තේ, ගෝඨාභය රාජපක්ෂගේ ප්\u200dරධානත්වයෙන් යුත් අලුත් ආණ්ඩුවකි. ඒ ආණ්ඩුව පටන් ගත් දා සිට පොලිසිය දඩයම් කිරීමට පටන්ගෙන තිබේ. නම් වශයෙන් ගත් කල ඒ ලේඛනය හත්සිය ගණනක් ඉක්මවා යන ලේඛනයකි. ආණ්ඩුව පටන් ගත් වහා\u2009ම ආණ්ඩුවෙන් බේරීමට පොලිස් පරීක්ෂක නිශාන්ත සිල්වා රට හැර ගියේ\u2009ය.\nදැන් ආණ්ඩුවේ ඊ\u2009ළඟ ගොදුර\u2009වී ඇත්තේ අපරාධ පරීක්ෂණ දෙපාර්තමේන්තුවේ අධ්\u200dයක්ෂ ජ්\u200dයෙෂ්ඨ පොලිස් අධිකාරී ශානි අබේසේකරය. ආණ්ඩු පාක්ෂිකයන්ට අනුව ශානි යනු පැවැති ආණ්ඩුවට අවශ්\u200

Clean

In [ ]:
import re
from itertools import chain

def preprocess_text(text):
    # Split by period '.'
    sentences = text.split('.')

    processed_sentences = []
    for sentence in sentences:
        # Remove English letters
        sentence = re.sub(r'[a-zA-Z]', '', sentence)

        # Remove punctuation and special characters (retain Sinhala letters)
        sentence = re.sub(r'[^\u0D80-\u0DFF\s]', '', sentence)  # Unicode range for Sinhala is \u0D80 to \u0DFF

        # Remove extra whitespace
        sentence = re.sub(r'\s+', ' ', sentence).strip()

        if sentence:  # Add sentence if not empty after cleaning
            processed_sentences.append(sentence)

    # Return the processed text as a single string, joined by periods
    return processed_sentences

# Apply the preprocessing to the entire dataset
processed_texts = [preprocess_text(text) for text in texts]
print(processed_texts[:5])

# Flatten the list of lists into a 1-dimensional list of sentences
all_sentences = list(chain.from_iterable(processed_texts))
print(all_sentences[:10])

[['පොලිස් කොමිසමෙන් පියන් කෙනකු කළ ශානිගේ කතාව', 'පොලිස් කොමිසමෙන් පියන් කෙනකු කළ ශානිගේ කතාව', 'ගෝඨාභය රාජපක්ෂ යනු හිටපු හමුදා නිලධාරියෙකි', 'පසු කලෙක ආරක්ෂක අමාත්යාංශයේ ලේකම්වරයා වශයෙන් ද කටයුතු කළ අයෙකි', 'දැන් මෙරට ජනාධිපතිවරයාය', 'ඔහු ජනාධිපතිවරණ සටනේදී පුන පුනා කීවේ පැවැති ආණ්ඩුව ඔවුන් විසින් රණවිරුවන් ලෙසින් හැඳින් වූ අයව දඩයම් කරන බවය', 'එනිසා එකී දඩයක්කාර ආණ්ඩුව ගෙදර යැවිය යුතු බව ඔවුන්ගේ මැතිවරණයේ ප්රධාන සටන් පාඨය විය', 'දැන් ඒ ආණ්ඩුව ගෙදර ගොස් ඇත', 'ඇත්තේ ගෝඨාභය රාජපක්ෂගේ ප්රධානත්වයෙන් යුත් අලුත් ආණ්ඩුවකි', 'ඒ ආණ්ඩුව පටන් ගත් දා සිට පොලිසිය දඩයම් කිරීමට පටන්ගෙන තිබේ', 'නම් වශයෙන් ගත් කල ඒ ලේඛනය හත්සිය ගණනක් ඉක්මවා යන ලේඛනයකි', 'ආණ්ඩුව පටන් ගත් වහා ම ආණ්ඩුවෙන් බේරීමට පොලිස් පරීක්ෂක නිශාන්ත සිල්වා රට හැර ගියේ ය', 'දැන් ආණ්ඩුවේ ඊ ළඟ ගොදුර වී ඇත්තේ අපරාධ පරීක්ෂණ දෙපාර්තමේන්තුවේ අධ්යක්ෂ ජ්යෙෂ්ඨ පොලිස් අධිකාරී ශානි අබේසේකරය', 'ආණ්ඩු පාක්ෂිකයන්ට අනුව ශානි යනු පැවැති ආණ්ඩුවට අවශ්ය ලෙස නීතිය නැමූ රූකඩයෙකි', 'ඒ අයට ම අනුව ශානි කර ඇත්තේ රණවිරු දඩයම්ය', 'රාජපක්ෂලා පසුපස හඹා යාමය', 'අපට 

Tokenize

In [ ]:
import tensorflow as tf

# Setup vocab size
# vocab_size = 20000

# Initialize the tokenizer
tokenizer = tf.keras.preprocessing.text.Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(all_sentences)

# Convert sentences to sequences of integers
sequences = tokenizer.texts_to_sequences(all_sentences)
print(sequences[:5])

# Test
print(tokenizer.sequences_to_texts(sequences[:5]))

[[305, 12126, 5441, 3833, 14, 17319, 306], [305, 12126, 5441, 3833, 14, 17319, 306], [1018, 295, 200, 249, 439, 22426], [109, 5794, 398, 1648, 2643, 84, 7, 52, 14, 6212], [50, 488, 33238]]
['පොලිස් කොමිසමෙන් පියන් කෙනකු කළ ශානිගේ කතාව', 'පොලිස් කොමිසමෙන් පියන් කෙනකු කළ ශානිගේ කතාව', 'ගෝඨාභය රාජපක්ෂ යනු හිටපු හමුදා නිලධාරියෙකි', 'පසු කලෙක ආරක්ෂක අමාත්යාංශයේ ලේකම්වරයා වශයෙන් ද කටයුතු කළ අයෙකි', 'දැන් මෙරට ජනාධිපතිවරයාය']


Set up MLM goal

In [ ]:
import random
import numpy as np

mask_token = "<MASK>"
sequence_length = 50

# Add the mask token to the tokenizer
mask_token_idx = len(tokenizer.word_index) + 1
tokenizer.word_index[mask_token] = mask_token_idx
tokenizer.index_word[mask_token_idx] = mask_token

# Update vocab_size to include the mask token
# vocab_size += 2  # +1 for OOV and +1 for MASK

# Pad sequences to the same length
padded_sequences = tf.keras.preprocessing.sequence.pad_sequences(sequences, maxlen=sequence_length, padding='post', truncating='post')
print(padded_sequences[:5])

# Function to create masked inputs and target outputs
def create_masked_inputs(sequences, mask_token_id, mask_prob=0.15):
    input_ids = []
    target_ids = []

    for seq in sequences:
        mask_prob_itter = mask_prob
        input_seq = []
        target_seq = []
        for token_id in seq:
            if token_id == 0:
                # Padding token, no prediction
                input_seq.append(0)
                target_seq.append(0)
            else:
                if random.random() < mask_prob_itter:
                    input_seq.append(mask_token_id)  # Replace with [MASK]
                    target_seq.append(token_id)      # Original token as target
                    mask_prob_itter -= 0.05
                else:
                    input_seq.append(token_id)       # Original token
                    target_seq.append(mask_token_id) # No prediction
                    mask_prob_itter += 0.05
        input_ids.append(input_seq)
        target_ids.append(target_seq)

    return np.array(input_ids), np.array(target_ids)

# Create masked inputs and targets
input_ids, target_ids = create_masked_inputs(padded_sequences, mask_token_idx)
print(input_ids[0])
print(target_ids[0])

# Test by converting sequences to words
print(tokenizer.sequences_to_texts(input_ids[:5]))
print(tokenizer.sequences_to_texts(target_ids[:5]))

# Print length
print(len(input_ids))

[[  305 12126  5441  3833    14 17319   306     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0]
 [  305 12126  5441  3833    14 17319   306     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0]
 [ 1018   295   200   249   439 22426     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0]
 [  109  5794   398  1648  2643    84     7    52    14  6212     0

In [ ]:
test_tokens = [74935, 305, 0, 74936, 20000, 19999, 20001, 19998]
print(tokenizer.sequences_to_texts([test_tokens]))
# get tokenizer length
print(len(tokenizer.word_index))

['<MASK> පොලිස් <OOV> <OOV> චතුත්තත් චතුත් ප්රත්යයෙන් සද්දය']
74935


#### Set up training model

Imports and initialization

In [ ]:
import numpy as np
import tensorflow as tf

# Set random seed for reproducibility
np.random.seed(42)
tf.random.set_seed(42)



Define Loss Function to Exclude Masks

In [ ]:
@tf.keras.saving.register_keras_serializable('custom_loss')
def masked_loss_function(y_true, y_pred):
    """
    Calculates the masked loss for the MLM task.

    Args:
        y_true: Ground truth labels (tensor).
        y_pred: Predicted labels (tensor).

    Returns:
        The masked loss value (scalar).
    """
    # Ensure y_true has the correct shape for sparse_categorical_crossentropy
    y_true = tf.squeeze(y_true, axis=-1)  # Remove the extra dimension
    print(y_true, y_true.shape)

    # Calculate the loss
    loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    print(loss, loss.shape)

    # Create a mask to ignore padding tokens (represented by 0)
    mask = tf.cast(tf.math.not_equal(y_true, 0), dtype=loss.dtype)
    print(mask, mask.shape)

    # Apply the mask to the loss
    masked_loss = loss * mask
    print(masked_loss, masked_loss.shape)

    # Calculate the mean masked loss
    reduced_mean = tf.reduce_mean(masked_loss)
    print(reduced_mean)
    return reduced_mean

In [ ]:
seq_1 = np.expand_dims([0, 0, 43, 0, 0, 0], axis=-1)
seq_1_with_loss1 = np.array([[15, 42, 43, 23, 45, 67]])
seq_1_with_loss2 = np.array([[15, 42, 43, 23, 0, 0]])
seq_1_with_loss3 = np.array([[0, 0, 43, 0, 0, 0]])
seq_1_with_loss4 = np.array([[8, 8, 43, 8, 8, 0]])
seq_2 = np.expand_dims([8, 8, 43, 8, 8, 0], axis=-1)

# Reshape seq_1_with_loss1, seq_1_with_loss2, seq_1_with_loss3, seq_1_with_loss4
# to (batch_size, num_classes)
seq_1_with_loss1 = np.expand_dims(np.squeeze(seq_1_with_loss1), axis=-1)
seq_1_with_loss2 = np.expand_dims(np.squeeze(seq_1_with_loss2), axis=-1)
seq_1_with_loss3 = np.expand_dims(np.squeeze(seq_1_with_loss3), axis=-1)
seq_1_with_loss4 = np.expand_dims(np.squeeze(seq_1_with_loss4), axis=-1)


# Convert to one-hot encoding with 1000 classes
num_classes = 74936
seq_1_with_loss1 = tf.keras.utils.to_categorical(seq_1_with_loss1, num_classes=num_classes)
seq_1_with_loss2 = tf.keras.utils.to_categorical(seq_1_with_loss2, num_classes=num_classes)
seq_1_with_loss3 = tf.keras.utils.to_categorical(seq_1_with_loss3, num_classes=num_classes)
seq_1_with_loss4 = tf.keras.utils.to_categorical(seq_1_with_loss4, num_classes=num_classes)



print(masked_loss_function(seq_1, seq_1_with_loss1), end="\n\n")
print(masked_loss_function(seq_1, seq_1_with_loss2), end="\n\n")
print(masked_loss_function(seq_1, seq_1_with_loss3), end="\n\n")
print(masked_loss_function(seq_1, seq_1_with_loss4), end="\n\n")
print(masked_loss_function(seq_2, seq_1_with_loss4), end="\n\n")

tf.Tensor([ 0  0 43  0  0  0], shape=(6,), dtype=int64) (6,)
tf.Tensor(
[1.61255611e+01 1.61255611e+01 7.46556395e-03 1.61255611e+01
 1.61255611e+01 1.61255611e+01], shape=(6,), dtype=float64) (6,)
tf.Tensor([0. 0. 1. 0. 0. 0.], shape=(6,), dtype=float64) (6,)
tf.Tensor([0.         0.         0.00746556 0.         0.         0.        ], shape=(6,), dtype=float64) (6,)
tf.Tensor(0.0012442606581283678, shape=(), dtype=float64)
tf.Tensor(0.0012442606581283678, shape=(), dtype=float64)

tf.Tensor([ 0  0 43  0  0  0], shape=(6,), dtype=int64) (6,)
tf.Tensor(
[1.61255611e+01 1.61255611e+01 7.46556395e-03 1.61255611e+01
 7.46556395e-03 7.46556395e-03], shape=(6,), dtype=float64) (6,)
tf.Tensor([0. 0. 1. 0. 0. 0.], shape=(6,), dtype=float64) (6,)
tf.Tensor([0.         0.         0.00746556 0.         0.         0.        ], shape=(6,), dtype=float64) (6,)
tf.Tensor(0.0012442606581283678, shape=(), dtype=float64)
tf.Tensor(0.0012442606581283678, shape=(), dtype=float64)

tf.Tensor([ 0  0 43  0

Custom Self Attention Layer

In [ ]:
@tf.keras.saving.register_keras_serializable('simple_self_attention')
class SelfAttention(tf.keras.layers.Layer):
    def __init__(self, units, **kwargs):
        super(SelfAttention, self).__init__(**kwargs)
        self.units = units

    def build(self, input_shape):
        self.Wq = self.add_weight(shape=(input_shape[-1], self.units), initializer='random_normal', trainable=True)
        self.Wk = self.add_weight(shape=(input_shape[-1], self.units), initializer='random_normal', trainable=True)
        self.Wv = self.add_weight(shape=(input_shape[-1], self.units), initializer='random_normal', trainable=True)

    def call(self, inputs):
        Q = tf.matmul(inputs, self.Wq)  # Query
        K = tf.matmul(inputs, self.Wk)  # Key
        V = tf.matmul(inputs, self.Wv)  # Value

        # Calculate attention scores
        scores = tf.matmul(Q, K, transpose_b=True) / tf.sqrt(float(self.units))
        attention_weights = tf.nn.softmax(scores, axis=-1)

        # Apply attention weights to the values
        output = tf.matmul(attention_weights, V)
        return output

    def get_config(self):
        config = super().get_config()
        config.update({"units": self.units})
        return config

Build Model (to Predict Next Word)

In [ ]:
def build_model(vocab_size, embedding_dim, lstm_units, sequence_length, dropout_rate):
    # Input layer
    input_layer = tf.keras.layers.Input(shape=(sequence_length,))  # Input shape based on tokenized sequences

    # Embedding layer
    embedding_layer = tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=embedding_dim)(input_layer)

    # Bidirectional LSTM layer
    lstm_out = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(lstm_units, return_sequences=True))(embedding_layer)

    # Custom Self-Attention layer
    attention_out = SelfAttention(units=lstm_units, name='self_attention_layer')(lstm_out)

    # Output layer to predict the masked token
    output = tf.keras.layers.Dense(vocab_size, activation='softmax', name='output')(attention_out)

    # Create the model
    model = tf.keras.models.Model(inputs=input_layer, outputs=output)

    # Compile the model
    model.compile(optimizer='adam', loss=masked_loss_function, metrics=['accuracy'])

    return model

Build model with hyperparameters

In [ ]:
# Hyperparameters
vocab_size = len(tokenizer.word_index) + 1        # Number of unique tokens in your vocabulary
embedding_dim = 256                               # Dimensionality of the embedding space
lstm_units = 128                                  # Number of units in LSTM layer
dropout_rate = 0.5                                # Dropout rate for regularization

# Initialize and summarize the model
mlm_model = build_model(vocab_size=vocab_size, embedding_dim=embedding_dim, lstm_units=lstm_units, sequence_length=sequence_length, dropout_rate=dropout_rate)
mlm_model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 50)]              0         
                                                                 
 embedding_1 (Embedding)     (None, 50, 256)           19183616  
                                                                 
 bidirectional_1 (Bidirecti  (None, 50, 256)           394240    
 onal)                                                           
                                                                 
 self_attention_layer (Self  (None, 50, 128)           98304     
 Attention)                                                      
                                                                 
 output (Dense)              (None, 50, 74936)         9666744   
                                                                 
Total params: 29342904 (111.93 MB)
Trainable params: 293429

Train for MLM Objective

In [ ]:
from sklearn.model_selection import train_test_split

# Expand target_ids to have an extra dimension for sparse_categorical_crossentropy
target_ids_expanded = np.expand_dims(target_ids, axis=-1)

# Split the data
train_input, val_input, train_target, val_target = train_test_split(input_ids, target_ids_expanded, test_size=0.2, random_state=42)

print(np.squeeze(val_target[:5], axis=-1))
print(input_ids.shape)
print(target_ids_expanded.shape)

[[    0     0     0     0     0     2     0     0   849     0    32   159
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0]
 [ 2391     0     0     0     0     0   360     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0]
 [   36   566     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0]
 [    0     0     0  5192     0    70     0     0     0     0  6716

In [ ]:
import os

# Define callbacks
checkpoint_path = '/content/drive/MyDrive/LLM_Tasks/Task 1/Embedding Layer/Models/mlm_model.keras'
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
checkpoint = tf.keras.callbacks.ModelCheckpoint(checkpoint_path, monitor='val_loss', save_best_only=True)

# Restoring from checkpoint
# Check if the checkpoint exists
if os.path.exists(checkpoint_path):
    # Load the saved model architecture from the checkpoint
    custom_objects = {'masked_loss_function': masked_loss_function, 'SelfAttention': SelfAttention}
    saved_model = tf.keras.models.load_model(checkpoint_path, custom_objects=custom_objects)

    # Compare model structures by their configuration
    if mlm_model.get_config() == saved_model.get_config():
        print("Model architectures match. Loading weights from checkpoint.")
        mlm_model.load_weights(checkpoint_path)
    else:
        print("Model architectures do not match. Starting from scratch.")
else:
    print("No checkpoint found. Starting from scratch.")

# Train the model
history = mlm_model.fit(
    train_input,
    train_target,
    epochs=20,
    verbose=1,
    batch_size=32,
    validation_data=(val_input, val_target),
    callbacks=[early_stopping, checkpoint]
)

Model architectures match. Loading weights from checkpoint.
Epoch 1/20
1097/1097 [==============================] - 739s 674ms/step - loss: 0.7545 - accuracy: 6.5705e-04 - val_loss: 0.8234 - val_accuracy: 0.0010
Epoch 2/20
1097/1097 [==============================] - 748s 682ms/step - loss: 0.7514 - accuracy: 0.0012 - val_loss: 0.8106 - val_accuracy: 0.0013
Epoch 3/20
1097/1097 [==============================] - 754s 687ms/step - loss: 0.7156 - accuracy: 0.0016 - val_loss: 0.8105 - val_accuracy: 0.0015
Epoch 4/20
1097/1097 [==============================] - 751s 685ms/step - loss: 0.6654 - accuracy: 0.0023 - val_loss: 0.8238 - val_accuracy: 0.0015
Epoch 5/20
1097/1097 [==============================] - 750s 684ms/step - loss: 0.6009 - accuracy: 0.0038 - val_loss: 0.8611 - val_accuracy: 0.0016
Epoch 6/20
 989/1097 [==========================>...] - ETA: 1:04 - loss: 0.5227 - accuracy: 0.0068

KeyboardInterrupt: 

Save Dynamic Embedding Layer

In [ ]:
import os

# Extract dynamic embedding component
attention_embedding_model = tf.keras.models.Model(inputs=mlm_model.input, outputs=mlm_model.get_layer('self_attention_layer').output)

def save_model_with_incremental_name(model, base_filename='attention_embedding_model', extension='.keras'):
    # Initialize the version counter
    version = 0
    filename = f"{base_filename}{extension}"

    # Check if the file exists and keep incrementing the version number
    while os.path.exists(filename):
        version += 1
        filename = f"{base_filename}_{version}{extension}"

    # Save the model with the final filename
    model.save(filename)
    print(f"Model saved as {filename}")

# Example usage:
save_model_with_incremental_name(attention_embedding_model)

Model saved as attention_embedding_model.keras


Testing

In [ ]:
# Evaluate error on test sequences
test_loss, test_accuracy = mlm_model.evaluate(val_input, val_target)
print(f"Test Loss: {test_loss}, Test Accuracy: {test_accuracy}")

275/275 [==============================] - 92s 333ms/step - loss: 0.9108 - accuracy: 0.0016
Test Loss: 0.9108313322067261, Test Accuracy: 0.001613859087228775


In [ ]:
# Predict on the first five validating sequences
predictions = mlm_model.predict(val_input[:5])

# Convert the input, predicted, and target sequences to readable text
input_texts = tokenizer.sequences_to_texts(val_input[:5])                             # Input sequences as text
predicted_texts = tokenizer.sequences_to_texts(np.argmax(predictions, axis=-1))       # Convert predicted sequences (use argmax to get token indices)
true_texts = tokenizer.sequences_to_texts(np.squeeze(val_target[:5], axis=-1))        # True target sequences as text
print(predictions.shape)
print(val_input[:5].shape)

# Print input sequences, predicted sequences, and true targets
for i in range(5):
    print(f"Input Sequence {i+1}: {input_texts[i]}")
    print(f"Predicted Sequence {i+1}: {predicted_texts[i]}")
    print(f"True Target {i+1}: {true_texts[i]}")
    print("-" * 50)

1/1 [==============================] - 0s 53ms/step
(5, 50, 74936)
(5, 50)
Input Sequence 1: සමහර විට දේශපාලන තක්කඩිකම් වලට <MASK> කොමිසම් සභා <MASK> ප්රමාණවත් <MASK> <MASK> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV>
Predicted Sequence 1: ඒ කොරියාව කොරියාව කොරියාව කොරියාව ද ඇති කොරියාව විශ්ව කළ කළ ය ය ය ය ය එස් එස් එස් එස් එස් එස් එස් සී සී සී සී මයා මයා මයා මයා මයා මයා සී සී සී සී සී සී මයා මයා ව ව ව ව ව ව ව ව ව
True Target 1: <OOV> <OOV> <OOV> <OOV> <OOV> මේ <OOV> <OOV> වාර්තාව <OOV> විය හැකිය <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV> <OOV>
--------------------------------------------------
Input Sequence 2: <MASK> පද්ධතියක් 